import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs';
const routes=JSON.parse(fs.readFileSync('routes.json','utf8'));
for(const width of [360,768,1440]){
  test(`all routes render without overflow at ${width}px`,async({page})=>{test.setTimeout(120000);await page.setViewportSize({width,height:950});const errors=[];page.on('pageerror',e=>errors.push(e.message));for(const {url} of routes){const response=await page.goto(url);expect(response.status(),url).toBe(200);await expect(page.locator('h1'),url).toBeVisible();const size=await page.evaluate(()=>({body:document.documentElement.scrollWidth,viewport:innerWidth}));expect(size.body,`${url} horizontal overflow`).toBeLessThanOrEqual(size.viewport+1);expect(await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>i.complete&&i.naturalWidth===0).map(i=>i.src)),url).toEqual([]);}expect(errors).toEqual([]);});
}
test('client and insight filters show matches and empty states',async({page})=>{await page.goto('/clients');await page.getByRole('searchbox').fill('UIDAI');await expect(page.locator('.client-tile:visible')).toHaveCount(1);await page.getByRole('searchbox').fill('no matching organization');await expect(page.locator('.empty-state')).toBeVisible();await page.goto('/insights');await page.locator('[data-category-select]').selectOption('Company News');await expect(page.locator('.article-card:visible')).toHaveCount(0);await expect(page.locator('.empty-state')).toBeVisible();await page.locator('[data-category-select]').selectOption('HR Insights');await expect(page.locator('.article-card:visible')).toHaveCount(1);});
test('job filters combine and reset; archived roles do not offer applying',async({page})=>{await page.goto('/careers/jobs');await page.locator('[data-status-select]').selectOption('closed');await expect(page.locator('.job-card:visible')).toHaveCount(2);await page.locator('[data-location-select]').selectOption('Navi Mumbai');await expect(page.locator('.job-card:visible')).toHaveCount(1);await page.getByRole('button',{name:'Clear filters'}).click();await expect(page.locator('.job-card:visible')).toHaveCount(4);await page.goto('/careers/jobs/mts-navi-mumbai');await expect(page.getByRole('link',{name:'Application guidance'})).toHaveCount(0);await expect(page.locator('.job-status')).toContainText('Closed');await page.goto('/careers/apply?job=technical-architect-bengaluru');await expect(page.locator('#application-guidance')).toContainText('deadline has passed');await expect(page.locator('#original-application')).toContainText('archived');});
test('contact validates and prepares a truthful email draft',async({page})=>{await page.goto('/contact?service=contract-staffing');await expect(page.locator('select[name=service]')).toHaveValue('contract-staffing');await page.getByRole('button',{name:'Prepare enquiry'}).click();await expect(page.locator('#form-error')).toBeVisible();await page.getByLabel('Full name').fill('Preview Test');await page.getByLabel('Company *').fill('Example Organization');await page.getByLabel('Business email').fill('preview@example.com');await page.getByLabel('Phone *').fill('+91 9000000000');await page.getByLabel('How can we help?').fill('Test enquiry for workforce support across two locations.');await page.getByLabel('I agree to include').check();await page.getByRole('button',{name:'Prepare enquiry'}).click();await expect(page.locator('#form-result')).toBeVisible();await expect(page.locator('#form-result')).toContainText('Nothing has been sent yet');await expect(page.getByRole('link',{name:'Open email draft'})).toHaveAttribute('href',/^mailto:info@gadigital.in/);const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download enquiry as text'}).click();expect((await downloadPromise).suggestedFilename()).toBe('ga-digital-business-enquiry.txt');});
test('mobile menu and FAQ support keyboard interaction',async({page})=>{await page.setViewportSize({width:360,height:800});await page.goto('/');const menu=page.getByRole('button',{name:'Menu'});await menu.click();await expect(menu).toHaveAttribute('aria-expanded','true');await page.keyboard.press('Escape');await expect(menu).toHaveAttribute('aria-expanded','false');await page.goto('/services/contract-staffing');const summary=page.locator('summary').first();await summary.focus();await page.keyboard.press('Enter');await expect(page.locator('details').first()).toHaveAttribute('open','');});
for(const url of ['/','/contact','/careers/jobs','/services/contract-staffing','/about/leadership','/clients','/public-notices'])test(`WCAG A/AA check ${url}`,async({page})=>{await page.goto(url);const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(result.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}))).toEqual([]);});
test('capture desktop and mobile layouts',async({page})=>{fs.mkdirSync('artifacts',{recursive:true});await page.setViewportSize({width:1440,height:1000});await page.goto('/');await page.screenshot({path:'artifacts/home-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.goto('/');await page.screenshot({path:'artifacts/home-mobile.png',fullPage:true});await page.goto('/contact');await page.screenshot({path:'artifacts/contact-mobile.png',fullPage:true});});
