import {company} from './site-data.mjs';
const contact=`<a href="mailto:${company.email}">${company.email}</a> or <a href="tel:${company.tel}">${company.phone}</a>. Postal address: ${company.address}.`;
const policies={
'Privacy Policy':[
['Who this notice covers',`This notice describes personal information handled through the GA Digital Web Word Pvt. Ltd. website and enquiries sent to the company. It does not replace a separate employee, candidate, client or supplier notice provided for a specific engagement. For privacy questions, contact ${contact}`],
['Information you choose to provide','The business enquiry form asks for your name, company, business email, phone number, service requirement and message. Designation is optional. Please provide only information relevant to your enquiry. Do not enter passwords, Aadhaar numbers, bank details, medical records or another person\'s confidential information in the general enquiry form.'],
['How the enquiry form works','Selecting “Prepare enquiry” creates a draft in your browser; it does not submit the form to a website database or send an email. “Open email draft” passes the enquiry to your email application. GA Digital receives it only if you send it. “Download enquiry as text” saves a file to your device. Your email provider, browser autofill and downloaded files have their own storage settings. The website code does not save form entries to local storage.'],
['Information generated when you visit','The website saves your selected preview theme in browser local storage. The current website code includes no analytics, advertising pixels or visitor profiling scripts. Hosting, access-control and network providers may process technical information such as IP addresses, request times and browser information to deliver and protect the site; their practices depend on the hosting environment.'],
['Google Maps and external services','Office pages embed Google Maps. When an embedded map loads, your browser connects to Google, which may receive technical information and use cookies or similar technologies under its own policies. The map may load when it approaches the visible part of the page; no separate map-consent control is currently implemented. External links, including maps, vacancy notices and any supplied LinkedIn profiles, take you to independently operated services. See <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google\'s Privacy Policy</a> and our <a href="/cookie-policy">Cookie Policy</a>.'],
['Why information is used','Information received in an enquiry is intended to help respond to your request, discuss services, coordinate follow-up, maintain relevant correspondence and address misuse or legal requirements. A general enquiry does not register you for a job, create an employment relationship or subscribe you to marketing. Separate recruitment or service processes may require additional information and notices.'],
['Access and disclosure','Enquiry correspondence may need to be handled by the relevant company team and the email or IT providers used to process it. Information may also need to be disclosed where required by law or to address fraud, security incidents or legal claims. This website does not implement a sale of visitor data or advertising-audience sharing. Company-wide disclosure arrangements must be confirmed before this draft is adopted.'],
['Retention and security','The theme preference has no expiry set by the website and remains until cleared or replaced by your browser. The website code does not maintain a submitted-enquiry database. Retention of received emails, provider logs and recruitment records depends on the relevant business process and legal obligations; a company-approved retention schedule has not been supplied for this draft. No online transmission or storage system can be guaranteed completely secure. Avoid sending unnecessary sensitive information.'],
['Your choices and requests',`You can choose not to send an enquiry, clear browser storage, restrict third-party cookies or contact the company about information you have supplied. Requests for access, correction, deletion or withdrawal of consent will need to be considered under the law applicable at the time and any relevant record-keeping requirements. Contact ${contact} Include enough context to identify the enquiry, but do not send identity documents unless a secure verification method is arranged. You may also use any complaint channels available under applicable law.`],
['Children and updates','This is a business and workforce information website, not a service directed at children. A parent or guardian who believes a child has sent unnecessary personal information should contact the company. Material changes to website functions or data handling should be reflected in this notice and its revision date.']
],
'Cookie Policy':[
['Cookies and browser storage','Cookies are small values saved by websites or service providers in your browser. Local storage is a separate browser-storage mechanism. This policy distinguishes the website\'s theme preference from cookies that a third-party service or hosting provider may use.'],
['Storage used by this website','The current website code does not set first-party cookies and does not include analytics or advertising trackers. It uses local storage under the key <code>ga-preview-theme</code> to remember Warm Editorial, Classic Corporate or Fresh Blue &amp; Teal. The stored value is the theme identifier, not your enquiry details. It is saved automatically when a theme is applied and has no expiry configured by the website. A <code>theme</code> URL parameter can override the saved choice.'],
['Embedded Google Maps','Google Maps is embedded on the contact and office-location pages. Loading a map makes a request to Google and may involve Google cookies, existing Google-account settings or similar technologies. Names and lifetimes vary with Google\'s service, region and browser settings; this website does not maintain a fixed inventory of Google cookies. Read <a href="https://policies.google.com/technologies/cookies" target="_blank" rel="noopener noreferrer">How Google uses cookies</a> and <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google\'s Privacy Policy</a>.'],
['Hosting and external links','A deployed host or sign-in layer may use storage for access control, sessions or security. These are separate from the static website code and depend on the deployment. Following an external link subjects your visit to that service\'s own storage practices.'],
['Managing your choices','You can clear this site\'s cookies and site data in your browser settings to remove the saved theme. Browser controls can also restrict third-party cookies and storage; maps or other external features may then behave differently. Clearing the theme preference resets it, but a subsequent visit may save the default theme again. This version has no cookie-consent banner, granular consent manager or automatic blocking of embedded maps.'],
['Changes and contact',`If analytics, additional embeds or other storage are introduced, this inventory and any required choice controls should be updated before use. For questions, contact ${contact} See also the <a href="/privacy-policy">Privacy Policy</a>.`]
],
'Terms & Conditions':[
['About this website',`This website provides information about ${company.name}, its workforce-related services, office contacts and published opportunities. These terms concern website use. A signed service agreement, employment contract or applicable recruitment notification governs the relevant engagement and takes priority for that engagement.`],
['Using the information','Content is provided for general information and may change. Confirm availability, scope, eligibility, timelines and commercial terms directly with the company before relying on information for a decision. An enquiry or website visit does not create a service contract, appointment, job offer or guarantee of a response.'],
['Acceptable use','Use the site lawfully. Do not attempt unauthorized access, disrupt its availability, introduce malicious code, impersonate another person or submit misleading or unlawfully obtained information. Do not use contact details for spam or harassment. You are responsible for the accuracy and lawful sharing of information you choose to send.'],
['Enquiries and communications','The enquiry tool prepares an email draft or downloadable text file. It does not send a message automatically. Review the recipient and content before sending through your email provider. Service proposals and commitments must be confirmed by an authorized company representative through the appropriate business process.'],
['Recruitment information','Vacancy summaries are provided for navigation. The original notification governs eligibility, deadlines, application steps and any stated terms. A listed or archived vacancy is not proof of a current opening. Do not rely on a website listing as a job offer. Read the <a href="/recruitment-disclaimer">Recruitment Disclaimer</a> and <a href="/careers/recruitment-fraud-alert">Recruitment Fraud Alert</a>, and verify doubtful communications through company contact channels.'],
['Content, names and intellectual property','Website content and assets may belong to GA Digital, their original creators or other rights holders. Organization names, logos and trademarks remain the property of their respective owners. Portfolio listings do not imply endorsement or a current contract. Do not reuse content beyond permission, licence terms or rights provided by applicable law.'],
['Illustrations and draft content','Profiles, portraits, testimonials, messages or policy text explicitly labelled illustrative, sample or draft are provided for review and are not verified statements or endorsements. Theme previews are alternative presentations of the same website content. Certification scope and validity should be confirmed with the company.'],
['Third-party services','Google Maps, email applications, external profile pages and vacancy documents are operated independently. Their availability, content and privacy practices are governed by their own providers. Linking to them does not guarantee their accuracy or availability.'],
['Availability and responsibility','The site may be updated, interrupted or unavailable. No promise is made that it will be uninterrupted or free from errors. To the extent permitted by applicable law, the company does not accept responsibility for losses caused solely by reliance on general website information or independently operated third-party services. Nothing in these terms excludes any liability or right that cannot lawfully be excluded.'],
['Privacy, questions and changes',`Read the <a href="/privacy-policy">Privacy Policy</a> and <a href="/cookie-policy">Cookie Policy</a> for website data handling. Raise website questions or concerns at ${contact} Applicable law and any separate agreement govern legal rights and disputes. Updates should carry a revised date; changes do not override mandatory legal rights or separately agreed contractual terms.`]
]};
export function policyContent(title){return `<div class="policy-document"><p class="policy-draft-note"><strong>Draft for company review.</strong> Prepared for the current website on 8 October 2026. Company approval and legal review are pending.</p><nav class="policy-links" aria-label="Website policies"><a href="/privacy-policy">Privacy Policy</a><a href="/cookie-policy">Cookie Policy</a><a href="/terms-conditions">Terms &amp; Conditions</a><a href="/recruitment-disclaimer">Recruitment Disclaimer</a></nav>${policies[title].map(([heading,body],i)=>`<section><h2>${i+1}. ${heading}</h2><p>${body}</p></section>`).join('')}</div>`;}
